services:
  database:
    image: mysql:9.2
    environment:
      MYSQL_DATABASE: datascientist
      MYSQL_ROOT_PASSWORD: datascientist_password
    volumes:
      - ./volumes/database:/var/lib/mysql
    ports:
      - '3306:3306'