services:
  database:
    image: mysql:9.2
    environment:
      MYSQL_DATABASE: datascientist
      MYSQL_USER: datascientistuser
      MYSQL_PASSWORD: datascientistpassword
      MYSQL_ROOT_PASSWORD: CHANGEME
    volumes:
      - ./volumes/database:/var/lib/mysql
    ports:
      - '3306:3306'